// <auto-generated />
namespace CarManagmentSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class storesData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(storesData));
        
        string IMigrationMetadata.Id
        {
            get { return "202401151922411_storesData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
